### ISSUE TITLE
Cannot compile with Visual Studio 2017

### ISSUE THREAD

**Issue by Galad** [AArnott/ImmutableObjectGraph#96]
Hello,
Compiling with Visual Studio 2017 produces an error in the output window:

    The "GenerateCodeFromAttributes" task failed unexpectedly.
    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Le fichier spécifié est introuvable.
    File name: 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
       at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
       at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
       at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(String assemblyName, String typeName)
       at System.AppDomain.CreateInstance(String assemblyName, String typeName)
       at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
       at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
       at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

I updated the CodeGeneration.Roslyn package. Now another error is returned when compiling:

    The "GenerateCodeFromAttributes" task failed unexpectedly.
    System.ArgumentException: Object type cannot be converted to target type.
       at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
       at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Code generation at design time does not work either.
I imagine it has to do with CodeGeneration.Roslyn moving to dotnet standard instead portable. It is probably related to #87 

Using Visual Studio 2017 Professional.

**Comment by AArnott** [comment]
Based on the error you saw, I believe I've fixed the missing build dependency on a machine with only VS2017 installed.

Regarding the trouble you're seeing with CodeGeneration.Roslyn, its latest version has some issues as I'm trying hard to get that to work on .NET Framework as well as CoreCLR on both Windows and Linux, which is evidently a really hard balancing act.

**Comment by Galad** [comment]
Hello,
Thank you for your answer.
What I meant was, when I:
- Create a new project in Visual Studio 2017
- Then add the ImmutableObjectGraph NuGet package
- Then create a class with the attribute [GenerateImmutable]
- Then compile
I get the error above.

The commit you did only change test projects so I don't think it can fix my issue.

Note that I have both 2015 and 2017 installed.

**Comment by AArnott** [comment]
Ah, I think I misunderstood your issue and thought you were building this repo and getting the break there.

**Comment by AdmiralSnyder** [comment]
The problem still persists.
where is the dependancy on Microsoft.Build.Utilities.Core, Version=14.0.0.0 coming from?
i had hoped that recreating CodeGeneration.Roslyn.Tasks with VS2017 is sufficient but that's not the case.

@AArnott have you considered creating a fork of CodeGeneration.Roslyn and ImmutableObjectGraph depending on .netStandard only? this could get us rid of all the portable stuff hopefully reducing complexity and increasing upgradeability. (because the targetframework problem mentioned [here   ](https://github.com/AArnott/CodeGeneration.Roslyn/issues/52) occurs when i try to build ImmutableObjectGraph, too. but it doesn't seem to be solved so easy...)

**Comment by AArnott** [comment]
No MSBuild Task can depend on .NETStandard only due to MSBuild on the .NET Framework not guaranteeing that .NET Standard façade assemblies are present at runtime.
I believe you're seeing this because you don't have MSBuild 14 installed. But I see that IOG depends on a rather old version of CG.R and perhaps updating it all properly from within the IOG repo will resolve the issue. I'll give it a try.

**Comment by AArnott** [comment]
Fixed by 2d6a1b83cf2c29937464e48dbaff44d82ce532d7

**Comment by AdmiralSnyder** [comment]
Thanks. Was it much manual work? Your commit included many changes to the Assert methods you used, can those be filtered out?

**Comment by AArnott** [comment]
Yes it was a lot of work. It included package dependency updates like xunit that brought build warnings that the assertion fixes addressed.
While it could possibly be more minimal. Of a change, why would that be interesting?
